name: tfm_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base
  - r-tidyverse
  - r-ggplot2
  - r-readr
  - r-dplyr
  - bioconductor-clusterprofiler
  - bioconductor-org.hs.eg.db
  - bioconductor-reactomepa
  - bioconductor-enrichplot
  - bioconductor-dose
  - bioconductor-limma
  - snakemake
  - vcftools
  - plink
  - multiqc
  - r-fs
  - r-tibble
  - bioconductor-annotationdbi
